### PR TITLE
Component will not call render after it has been unmounted

### PR DESCRIPTION
**Pull request by ttsahi**
We had a bug using this library when the angular onChanges hook was called after the component was already destroyed. When onChange occurs it calls render on the element. So, if an onChange occurs after an element is destroyed, the whole element is created again for no reason. Each time this happens it will add an element to the Dom with no reference. These are detached Dom nodes which won't be deleted and create a memory leak.

We added a simple fix which stops the render function creating an element after the component was unmounted. We wanted to add a test to prove this, but it seems that the library hasn't been updated in a while and none of the tests currently run. We saw this fix works for our project and would be happy to add our test after the library is fixed.

### CODE REVIEW

**Comment by ttsahi** [comment]
We fixed the tests but the circleci is failing. The configuration and how the tests are running seems completely different. Any idea why?

**Comment by ttsahi** [comment]
We rebased, added the test, and made some other small changes:

- Changed circleci config image to `circleci/node:8.9-browsers` because tests needed a browser to run
- Added .idea to .gitignore and .npmignore so that webstorm files won't be added
- Changed clean from rm to rimraf in package.json because we work on windows
- Changed angular-mocks version to 1.6.9 because [tests wouldn't run](https://stackoverflow.com/questions/51788388/angular-js-1-6-9-tests-unknown-provider-tasktrackerfactoryprovider)
- Added -fix to tslint script in package.json
- Added skipLibCheck so that tsconfig won't check other libraries and excluded node_modules

**Comment by ttsahi** [comment]
Hey @bcherny, I fixed the issues and think we're ready for a pull request review.

**Comment by bcherny** [comment]
Published `4.0.6`

**Pull request merged**
