### PR TITLE
add support for nullable bindings

### PR DESCRIPTION
**Pull request by bcherny**

### CODE REVIEW

**Comment by chrisgarber** [comment]
Shouldn't we use the ternary operator at line 64 to check if the propTypes definition is optional?

**Comment by bcherny** [comment]
@chrisgarber I can't find a clean way to check if the propTypes definition is optional. Can you?

**Comment by chrisgarber** [comment]
So my thought was to check the isRequired property. If it has an isRequired property then it is the parent type and thus not required. I haven’t tested it yet since I’ve been having trouble getting the build to run. It should look something like:

>mapValues(Class.propTypes, _ => (_ as PropTypes.Requirable).isRequired?”<?”:”<“

I’m not sure if it will work, but that’s my best shot.

**Comment by bcherny** [comment]
> I’ve been having trouble getting the build to run. It should look something like

What issues are you having?

**Comment by chrisgarber** [comment]
running `npm test` yields `missing script: clean;`

**Comment by bcherny** [comment]
@chrisgarber What version of NPM/Node are you using? Did you modify your local package.json?

**Comment by chrisgarber** [comment]
sorry I didn't get back over the weekend, I'm using npm 5.6.0 and node 6.11.1. No changes to the package file. When I run "npm run clean" I get a message that rm isn't a valid command. I'm on Windows if that makes a difference.

**Comment by bcherny** [comment]
Please use google to resolve your issue. You may have to use a cross-platform rm package from NPM instead of using rm directly.

**Comment by chrisgarber** [comment]
Getting the optional status from proptypes by checking isRequired works in my branch. If you replace line 64 with something like this:

`return mapValues(Class.propTypes, (_:keyof Props) => !(_ as PropTypes.Requireable<Props>).isRequired ? '<' : '<?')`

you should be able to do it with this code too. You will probably also have to import the prop-types library for the typing to work, and of course add a test for the prop-types only case.

**Comment by bcherny** [comment]
@chrisgarber Now that the scaffolding is set up, feel free to fork my branch and implement this. Again, from what I tried your code will not work. But maybe I missed something.

**Comment by chrisgarber** [comment]
I created a pull request to this branch with my changes. It passes the tests as expected and seems to be working well. Perseverance!

**Comment by bcherny** [comment]
Closing in favor of https://github.com/coatue-oss/react2angular/pull/64

**Pull request closed without merging**
